### ISSUE TITLE
Releasing version for Scala 2.12 and Play 2.8.*

### ISSUE THREAD

**Issue by gergelyfabian** [lucidsoftware/play_routes_compiler_cli#18]
I'd need support for Scala 2.12 and Play 2.8.8. There is already support for Play 2.8.* on Scala 2.13.

I'd be ready to contribute this to both play_routes_compiler and rules_play_routes.

For this repo I've created a branch in my fork, with the desired Play version: https://github.com/gergelyfabian/play_routes_compiler_cli/tree/2.12--2.8.8.

As the master branch in the history is upgrading in the same line both Scala and Play versions, this could be done diverging from historic master at the moment where Play 2.7 was introduced for Scala 2.12.
In my branch I excluded Scala dependencies for Play 2.8 to avoid upgrading Scala patch version (this would cause issues when compiling the compiler bridge). I'm not quite sure what to do with the test dependencies, even though I tried upgrading the Play version also there.

**Comment by SrodriguezO** [comment]
This shouldn't be too tricky, we'll just need to cherry-pick the CI commits that landed after your branch poibt. I can get this going tomorrow morning.

It's not a big deal, but for consistency w/ our other 2.8.* release, would Play 2.8.7 satisfy your use case?

**Comment by gergelyfabian** [comment]
Of course, any Play 2.8.* release would be great. Thank you very much!

Sergio Rodriguez Orellana ***@***.***> ezt írta (időpont:
2021. nov. 16., K 1:31):

> This shouldn't be too tricky, we'll just need to cherry-pick the CI
> commits that landed after your branch poibt. I can get this going tomorrow
> morning.
>
> It's not a big deal, but for consistency w/ our other 2.8.* release, would
> Play 2.8.7 satisfy your use case?
>

**Comment by gergelyfabian** [comment]
I've uploaded branch https://github.com/gergelyfabian/play_routes_compiler_cli/tree/2.12--2.8.7. This version is simpler as I did not need to exclude Scala dependencies from Play.
I also managed to fix tests by cherry-picking test changes from master.

**Comment by SrodriguezO** [comment]
Needed all the CI changes, so just went the other way and [reverted the Scala 2.13 upgrade commits and then applied the Play upgrade changes](https://github.com/lucidsoftware/play_routes_compiler_cli/commits/try-revert-to-scala-2-12-but-keep-play). Was running into a weird error building the compiler bridge and then realized that was another issue Sriraam had fixed in [his upgrade commit](https://github.com/lucidsoftware/play_routes_compiler_cli/commit/8d29bd157eecea7b8443c00bc2e0475a3842f53a).

[This CI run ](https://github.com/lucidsoftware/play_routes_compiler_cli/actions/runs/1469150151)should publish it to Sonatype, at which point we can release to Maven; I'll check back in on it in the morning.

**Comment by gergelyfabian** [comment]
Great thanks @SrodriguezO! I think your solution is better, as it's closer to master. It seems the CI run finished with success :)

**Comment by SrodriguezO** [comment]
Awesome. Sorry about the delay - the week got busy and suddenly it's Friday :facepalm: 

I just closed/released the staged repository - it should go live on Maven Central within a few hours. Please let me know if you can't find it later today.

**Comment by gergelyfabian** [comment]
I tried taking the released version, and somehow it fails with an error (when I try to use it through https://github.com/lucidsoftware/rules_play_routes/pull/48):

```
Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce
	at rulesplayroutes.routes.CommandLinePlayRoutesCompiler$.<init>(CommandLinePlayRoutesCompiler.scala:24)
	at rulesplayroutes.routes.CommandLinePlayRoutesCompiler$.<clinit>(CommandLinePlayRoutesCompiler.scala)
	at rulesplayroutes.routes.CommandLinePlayRoutesCompiler.main(CommandLinePlayRoutesCompiler.scala)
Caused by: java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

I guess there may be a problem in how I've set up https://github.com/lucidsoftware/rules_play_routes/pull/48 (especially the dependencies, as I see Scala 2.13 appearing in com.lucidchart:play-routes-compiler-cli_2.12:2.8.7's dependencies).

Generated the dependency jsons there with scripts/gen-deps.sh.

**Comment by SrodriguezO** [comment]
Hm do you have a small repro repo? AFAICT there are no Scala 2.13 dependencies on the published 2.12--2.8.7 cli

**Comment by gergelyfabian** [comment]
I think the PR for rules_play_routes I created is the repro.

I have put there together (as the previous examples showed the setup), a
single Play version for both Scala 2.12 and 2.13 and coursier resolved the
dependencies for these together in a single dependency tree. For earlier
Play versions this wasn't an issue.

However now compiler cli for Play 2.8 for both Scala 2.12 and 2.13 includes
e.g. a scala-library dependency (looking at the poms). This wasn't the case
for earlier Play versions.

Now if I put these two (compiler cli Play 2.8 + both scala versions) in a
single dependency tree, as was the convention in rules_play_routes, then
Scala 2.13 becomes a dep of the route complier cli also for Scala 2.12. You
can see that in the dependency tree json I committed in the
rules_play_routes PR.

I believe that either the way we generate dependency trees in
rules_play_routes should change or route compiler cli's exported
dependencies would need to be adjusted.


Sergio Rodriguez Orellana ***@***.***> ezt írta (időpont:
2021. nov. 19., P 22:57):

> Hm do you have a small repro repo? AFAICT there are no Scala 2.13
> dependencies on the published 2.12--2.8.7 cli
>

**Comment by gergelyfabian** [comment]
My take for a solution is the last commit in https://github.com/lucidsoftware/rules_play_routes/pull/48:

https://github.com/lucidsoftware/rules_play_routes/pull/48/commits/f6e60835501d3f164b9bf14118fe92bc9bd75512

Here I separated the dependency trees for Scala 2.12 and 2.13 for Play 2.8.

With this change it started working in my example repo (no small repro yet). I have an example play repository with Scala 2.13, I can try downgrading that to Scala 2.12 if it's still necessary.

**Comment by gergelyfabian** [comment]
@SrodriguezO, if you agree I'd propose closing this one, and continue the discussion in https://github.com/lucidsoftware/rules_play_routes/pull/48 (as play_routes_compiler_cli works, we just need to solve the dependency tree issue in rules_play_routes).

**Comment by SrodriguezO** [comment]
Sounds great; reviewed, commented, and approved that PR. Thanks @gergelyfabian !
